import { trpc } from "@/lib/trpc";
import { FileText, Plus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export function SupportTemplatesPanel({ organizationSlug }: { organizationSlug: string }) {
  const utils = trpc.useUtils(); const [name, setName] = useState(""); const [body, setBody] = useState(""); const templatesQuery = trpc.workspace.support.listTemplates.useQuery({ organizationSlug }, { enabled: Boolean(organizationSlug), retry: false });
  const create = trpc.workspace.support.createTemplate.useMutation({ onSuccess: async () => { setName(""); setBody(""); toast.success("تم حفظ قالب الدعم."); await utils.workspace.support.listTemplates.invalidate(); }, onError: error => toast.error(error.message) });
  if (!organizationSlug) return null;
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_8px_30px_rgba(23,35,61,.035)]"><div className="border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-violet-600" /><h2 className="text-sm font-bold text-slate-900">قوالب الردود</h2></div><p className="mt-1 text-xs text-slate-500">قوالب مؤسسية قابلة لإعادة الاستخدام، ولا تُرسل رسالة تلقائيًا.</p></div><div className="p-5"><div className="grid gap-3 md:grid-cols-[180px_1fr_auto]"><input value={name} onChange={event => setName(event.target.value)} placeholder="اسم القالب" className="h-10 rounded-xl border border-slate-200 px-3 text-xs outline-none focus:border-violet-400" /><input value={body} onChange={event => setBody(event.target.value)} placeholder="نص الرد" className="h-10 rounded-xl border border-slate-200 px-3 text-xs outline-none focus:border-violet-400" /><button disabled={create.isPending} onClick={() => { if (!name.trim() || !body.trim()) { toast.error("أدخل اسم القالب ونصه."); return; } create.mutate({ organizationSlug, name: name.trim(), body: body.trim() }); }} className="inline-flex h-10 items-center justify-center gap-1.5 rounded-xl bg-violet-600 px-3 text-xs font-bold text-white disabled:opacity-60"><Plus className="h-4 w-4" />حفظ</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{templatesQuery.isLoading ? <p className="text-xs text-slate-500">جارٍ تحميل القوالب…</p> : templatesQuery.error ? <p className="text-xs text-rose-700">تعذر تحميل القوالب.</p> : templatesQuery.data?.length ? templatesQuery.data.map(template => <article key={template.id} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-800">{template.name}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{template.body}</p></article>) : <p className="py-4 text-center text-xs text-slate-500">لا توجد قوالب محفوظة بعد.</p>}</div></div></section>;
}
