import { trpc } from "@/lib/trpc";
import { Activity, Banknote, RadioTower, UsersRound } from "lucide-react";

const metric = (label: string, value: string | number, hint: string, Icon: typeof Activity) => <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(23,35,61,.035)]"><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-500">{label}</span><span className="grid h-8 w-8 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon className="h-4 w-4" /></span></div><p className="mt-4 text-2xl font-bold tracking-tight text-slate-900">{value}</p><p className="mt-2 text-xs text-slate-500">{hint}</p></section>;

export function TenantReportsPanel({ organizationSlug }: { organizationSlug: string }) {
  const reportQuery = trpc.workspace.reports.summary.useQuery({ organizationSlug }, { enabled: Boolean(organizationSlug), retry: false });
  if (!organizationSlug) return <section className="rounded-2xl border border-dashed border-violet-200 bg-violet-50/60 p-5 text-xs text-slate-600">اختر مؤسسة أولًا لقراءة تقاريرها المقيّدة بسياق العضوية.</section>;
  if (reportQuery.isLoading) return <section className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-xs text-slate-500">جارٍ احتساب مؤشرات المؤسسة…</section>;
  if (reportQuery.error || !reportQuery.data) return <section className="rounded-2xl border border-rose-100 bg-rose-50/70 p-5 text-xs text-rose-700">تعذر تحميل التقرير؛ لم تُعرض بيانات بديلة.</section>;
  const report = reportQuery.data; return <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(23,35,61,.035)]"><p className="text-xs font-bold text-violet-600">لقطة المؤسسة</p><h2 className="mt-1 text-base font-bold text-slate-900">تقرير التشغيل والمالية</h2><p className="mt-2 text-xs leading-6 text-slate-500">يُحتسب من السجلات المتاحة حاليًا للمؤسسة المحددة، وليس من واجهة الراوتر أو RADIUS مباشرة.</p></section><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metric("الراوترات السليمة", `${report.routers.healthy} / ${report.routers.total}`, `${report.routers.attention} تحتاج متابعة`, RadioTower)}{metric("العملاء النشطون", report.customers.active, `من إجمالي ${report.customers.total} عميل`, UsersRound)}{metric("الجلسات النشطة", report.sessions.active, `من إجمالي ${report.sessions.total} جلسة مسجلة`, Activity)}{metric("فواتير غير مسددة", report.billing.outstanding, `${report.billing.paidInvoices} فاتورة مدفوعة`, Banknote)}</div><section className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_30px_rgba(23,35,61,.035)] md:grid-cols-3"><div><p className="text-xs text-slate-500">فواتير صادرة هذا الشهر</p><p className="mt-2 text-xl font-bold text-slate-900">{report.billing.issuedThisMonth}</p></div><div><p className="text-xs text-slate-500">تذاكر مفتوحة أو معلقة</p><p className="mt-2 text-xl font-bold text-slate-900">{report.support.open}</p></div><div><p className="text-xs text-slate-500">وقت الإنشاء</p><p className="mt-2 text-sm font-bold text-slate-700">{new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium", timeStyle: "short" }).format(report.generatedAt)}</p></div></section></div>;
}
